# Generated by Django 2.0.6 on 2020-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(default='活跃', max_length=12),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='活跃', max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (2, 'other'), (1, 'famale')], default=0),
        ),
    ]
