# Generated by Django 2.0.6 on 2020-11-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_day4', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
