# Generated by Django 2.0.6 on 2020-11-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_day4', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(choices=[(1, 'famale'), (2, 'other'), (0, 'male')], default=0)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
