# Generated by Django 2.0.6 on 2020-10-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20201029_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
