# Generated by Django 2.0.6 on 2020-10-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_department_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'famale'), (2, 'other')], default=0),
        ),
    ]
