# Generated by Django 2.0.6 on 2020-10-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20201029_2026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
