# Generated by Django 2.0.6 on 2020-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201104_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='is_site',
            field=models.BooleanField(default=1, verbose_name='是否是站外的链接'),
        ),
    ]
