# Generated by Django 2.0.6 on 2020-11-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201103_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('memory', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '手机',
                'verbose_name_plural': '手机',
                'db_table': 'api_phone',
            },
        ),
    ]
